
services:

  postgres:
    image: postgres:latest
    env_file: ".env"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: seapac
    command: ./start
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    env_file: ".env"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
  media_data:
  static_data:

nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    environment:
      VIRTUAL_HOST: seapac.nadic.ifrn.edu.br
      VIRTUAL_POST: 80
      LETSENCRYPT_HOST: seapac.nadic.ifrn.edu.br
    networks:
      - web-proxy
      - default
    restart: unless-stopped

  
